### ISSUE TITLE
Travis CI - Gem::Requirement::BadRequirementError

### ISSUE THREAD

**Issue by suriyaa** [bunto/bunto-compose#2]
Travis CI error:

``` bash
/home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/requirement.rb:89:in `parse': Illformed requirement ["~> "] (Gem::Requirement::BadRequirementError)
       /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/requirement.rb:119:in `block in initialize'
       /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/requirement.rb:119:in `map!'
       /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/requirement.rb:119:in `initialize'
       /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/requirement.rb:56:in `new'
       /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/requirement.rb:56:in `create'
       /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/dependency.rb:58:in `initialize'
       /home/travis/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.9/lib/bundler/dependency.rb:39:in `initialize'
       /home/travis/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.9/lib/bundler/dsl.rb:74:in `new'
       /home/travis/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.9/lib/bundler/dsl.rb:74:in `gem'
       /home/travis/build/bunto/bunto-compose/Gemfile:4:in `eval_gemfile'
       /home/travis/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.9/lib/bundler/dsl.rb:32:in `instance_eval'
       /home/travis/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.9/lib/bundler/dsl.rb:32:in `eval_gemfile'
       /home/travis/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.9/lib/bundler/dsl.rb:10:in `evaluate'
       /home/travis/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.9/lib/bundler/definition.rb:25:in `build'
       /home/travis/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.9/lib/bundler.rb:155:in `definition'
       /home/travis/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.9/lib/bundler/cli/install.rb:77:in `run'
       /home/travis/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.9/lib/bundler/cli.rb:145:in `install'
       /home/travis/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.9/lib/bundler/vendor/thor/command.rb:27:in `run'
       /home/travis/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.9/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
       /home/travis/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.9/lib/bundler/vendor/thor.rb:363:in `dispatch'
       /home/travis/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.9/lib/bundler/vendor/thor/base.rb:440:in `start'
       /home/travis/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.9/lib/bundler/cli.rb:9:in `start'
       /home/travis/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.9/bin/bundle:20:in `block in <top (required)>'
       /home/travis/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.9/lib/bundler/friendly_errors.rb:5:in `with_friendly_errors'
       /home/travis/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.9/bin/bundle:18:in `<top (required)>'
       /home/travis/.rvm/gems/ruby-2.2.0/bin/bundle:23:in `load'
       /home/travis/.rvm/gems/ruby-2.2.0/bin/bundle:23:in `<main>'
       /home/travis/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
       /home/travis/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
There was an error in your Gemfile, and Bundler cannot continue.
The command "eval bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}" failed 3 times.
The command "bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}" failed and exited with 4 during .
Your build has been stopped.
```

> See https://travis-ci.org/bunto/bunto-compose/builds/119817092!

**Comment by suriyaa** [comment]
> :white_check_mark: Fixed in the [**`0053bdd`**](https://github.com/bunto/bunto-compose/commit/0053bdd19c295c4d2cb9c1249b847ec3663dddaf) commit!
